### ISSUE TITLE
Use python3 for ejecting CD

### ISSUE THREAD

**Issue by eN0Rm** [jima80525/audio-book-cde#1]
change to 'python3' from 'python' in this line

python -c 'import os, sys, fcntl

**Comment by jima80525** [comment]
I'll try to get to this tonight!  You can do a PR if you want, but it's a pretty easy one, so I can pick it up as well.

Surprised that people are still using this! Hope you're finding it useful.

**Comment by jima80525** [comment]
Fixed!  Hope this helps.
